version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: culturaldb
    environment:
      POSTGRES_DB: culturaldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cultural-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: cultural-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cultural-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cultural-backend
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@postgres:5432/culturaldb
      REDIS_URL: redis://redis:6379
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
    networks:
      - cultural-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cultural-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - cultural-network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  cultural-network:
    driver: bridge